apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: victtows/frontend-projetodevops:latest
          ports:
            - containerPort: 80
          env:
            - name: API_BASE_URL
              value: "http://backend-service:3000"  # Nome do service do backend
