apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namePrefix: frontend-
commonLabels:
  app: frontend
images:
- name: Front-Projetodevops
  newName: victtows/Frontend-devops-k8s
  newTag: f1b8d1767f3b2d680b5c7f2be1dc17f5ee0b88c3
