apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namePrefix: frontend-
commonLabels:
  app: frontend
images:
- name: frontend
  newName: victtows/front-projetodevops
  newTag: 0d07f3ad784187f54ab8b5498544d71e6de27457
- name: frontend-projetodevops
  newName: victtows/frontend-projetodevops-k8s
  newTag: 39dc4e678bf8930ce266183b35fe5af82e59b730
- name: hello-fastapi
  newName: eduardosilvasc/hello-fastapi-k8s
  newTag: 492d185ec7b064bebc30876ea9fcfbea1eec4dd9
