apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namePrefix: frontend-
commonLabels:
  app: frontend
images:
- name: frontend
  newName: victtows/front-projetodevops
  newTag: 0d07f3ad784187f54ab8b5498544d71e6de27457
