apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namePrefix: frontend-
commonLabels:
  app: frontend
images:
- name: Front-Projetodevops
  newName: victtows/Frontend-devops-k8s
  newTag: eacf4917b07feb5f1f56d7b31940378218774507
