apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: LoadBalancer  # Use NodePort se estiver localmente
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
